ALTER TABLE "Organization"
ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'Africa/Lagos',
ADD COLUMN "dateFormat" TEXT NOT NULL DEFAULT 'MMM D, YYYY',
ADD COLUMN "timeFormat" TEXT NOT NULL DEFAULT '12h',
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'NGN';
