FROM node:22

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY apps/web/package*.json apps/web/

RUN npm install

COPY apps ./apps
COPY packages ./packages

WORKDIR /app/apps/web

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]