FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json apps/api/
COPY packages packages
RUN npm ci

COPY apps/api apps/api
COPY turbo.json ./
RUN npm run build --workspace=apps/api

EXPOSE 4000
CMD ["npm", "run", "start:prod", "--workspace=apps/api"]
